// <auto-generated />
namespace Day4_MVC_lab7___sol___Ali_Ahmed.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _4653 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_4653));
        
        string IMigrationMetadata.Id
        {
            get { return "202009151752096_4653"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
